apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-crt
spec:
  secretName: www-crt-secret
  dnsNames:
  - www.miyop.in
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io