apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: sample
        tier: frontend
        track: stable
    spec:
      containers:
      - name: sampleapp-container
        image: 475620901817.dkr.ecr.us-west-2.amazonaws.com/k8simagesregistery:app399
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: sample
    tier: frontend
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
