apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      tier: private-backend
      track: stable
  template:
    metadata:
      labels:
        app: sample
        tier: private-backend
        track: stable
    spec:
      containers:
      - name: sampleapi-container
        image: k8simagesregistery.azurecr.io/api:#{tag}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: private-backend
spec:
  selector:
    app: sample
    tier: private-backend
  ports:
  - port: 8090
    targetPort: 80
  type: ClusterIP